//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experienced
    {
        public int ExperiencedId { get; set; }
        public string Institution { get; set; }
        public string Degree { get; set; }
        public System.DateTime Beginning_year { get; set; }
        public System.DateTime Final_year { get; set; }
        public string Description { get; set; }
        public int Professor { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual Professor Professor1 { get; set; }
    }
}
